---
- name: Push Certificates
  hosts: nodes
  become: true
  tasks:
  - name: Copy CA Certificates
    synchronize:
      src: ../../ca-certs/
      dest: /etc/pki/ca-trust/source/anchors/
      use_ssh_args: yes

  - name: Update CA Trust
    command: /usr/bin/update-ca-trust extract

  - name: restart Docker
    service:
      name: docker
      state: restarted
