AWSTemplateFormatVersion: 2010-09-09
Description: Create a VPC v20170802-1430
Parameters:
  Owner:
    Type: String
    Default: FirstName LastName
  Project:
    Type: String
    Default: Openshift VPC Creation
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - prod
      - staging
      - sandbox
      - test
      - uat
      - dev
  DeleteAfter:
    Type: String
    Default: 00/00/201x
  VPCSubnetCidrBlock:
    Description: 10.0.0.0/16 = 10.0.0.0-10.0.255.255 = 256 Subnets = 65534 hosts
    Type: String
    Default: 10.0.0.0/16
    MinLength: '10'
    MaxLength: '18'
  AvailabilityZone1:
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d
      - us-east-1e
      - us-east-1f
      - us-west-1a
      - us-west-1b
      - us-west-1c
      - us-west-2a
      - us-west-2a
      - us-west-2a
  PublicSubnetCidrBlock1:
    Type: String
    Default: 10.0.1.0/24
    MinLength: '10'
    MaxLength: '18'
  PrivateSubnetCidrBlock1:
    Type: String
    Default: 10.0.4.0/24
    MinLength: '10'
    MaxLength: '18'
Metadata:
  TemplateAuthor: Benjamin Van Houten
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Ownership
        Parameters:
          - Owner
          - Project
          - Environment
          - DeleteAfter
      - Label:
          default: Subnets
        Parameters:
          - VPCSubnetCidrBlock
          - PublicSubnetCidrBlock1
          - PrivateSubnetCidrBlock1
          - AvailabilityZone1
    ParameterLabels:
      Owner:
        default: Team or Individual Owner
      DeleteAfter:
        default: Delete After Date
      VPCSubnetCidrBlock:
        default: VPC Subnet
      PublicSubnetCidrBlock1:
        default: Public Subnet 1
      PrivateSubnetCidrBlock1:
        default: Private Subnet 1
      AvailabilityZone1:
        default: Availability Zone 1
  'AWS::CloudFormation::Designer':
    c7f32c56-83fa-4b63-aa08-d3a0dd03de75:
      size:
        width: 60
        height: 60
      position:
        x: 1270
        'y': 20
      z: 1
      embeds: []
    40ea6922-a2db-4c32-882c-3016803e0987:
      size:
        width: 550
        height: 520
      position:
        x: 550
        'y': -130
      z: 1
      embeds:
        - 32c6ca3c-7eb1-4b0b-bbe3-cb854f52aaab
        - ec7cf0b8-12c0-4199-a48c-e54e015b225c
        - 4653b995-371c-4add-bd1d-b86b5559a692
        - 84f826b0-6248-4d87-b744-5412a253c8e6
    32c6ca3c-7eb1-4b0b-bbe3-cb854f52aaab:
      size:
        width: 150
        height: 150
      position:
        x: 880
        'y': 190
      z: 2
      parent: 40ea6922-a2db-4c32-882c-3016803e0987
      embeds: []
      dependson:
        - 40ea6922-a2db-4c32-882c-3016803e0987
    ec7cf0b8-12c0-4199-a48c-e54e015b225c:
      size:
        width: 150
        height: 150
      position:
        x: 630
        'y': 200
      z: 2
      parent: 40ea6922-a2db-4c32-882c-3016803e0987
      embeds: []
      dependson:
        - 40ea6922-a2db-4c32-882c-3016803e0987
    7f152eee-0108-433b-a2e8-584a05296cbb:
      source:
        id: 32c6ca3c-7eb1-4b0b-bbe3-cb854f52aaab
      target:
        id: ec7cf0b8-12c0-4199-a48c-e54e015b225c
      z: 2
    4653b995-371c-4add-bd1d-b86b5559a692:
      size:
        width: 170
        height: 180
      position:
        x: 880
        'y': -90
      z: 2
      parent: 40ea6922-a2db-4c32-882c-3016803e0987
      embeds:
        - ab79ddd6-62be-40d4-bb04-dcc350f38905
      dependson:
        - 40ea6922-a2db-4c32-882c-3016803e0987
    ab79ddd6-62be-40d4-bb04-dcc350f38905:
      size:
        width: 60
        height: 60
      position:
        x: 940
        'y': -30
      z: 3
      parent: 4653b995-371c-4add-bd1d-b86b5559a692
      embeds: []
      dependson:
        - 4653b995-371c-4add-bd1d-b86b5559a692
        - c7f32c56-83fa-4b63-aa08-d3a0dd03de75
    db636478-6f20-4326-bcf4-e585dea063da:
      source:
        id: 40ea6922-a2db-4c32-882c-3016803e0987
      target:
        id: c7f32c56-83fa-4b63-aa08-d3a0dd03de75
      z: 1
    84f826b0-6248-4d87-b744-5412a253c8e6:
      size:
        width: 150
        height: 150
      position:
        x: 620
        'y': -60
      z: 2
      parent: 40ea6922-a2db-4c32-882c-3016803e0987
      embeds: []
      dependson:
        - 40ea6922-a2db-4c32-882c-3016803e0987
    ff3b287f-4b9a-48bf-9907-7816948f5f21:
      source:
        id: 4653b995-371c-4add-bd1d-b86b5559a692
      target:
        id: 84f826b0-6248-4d87-b744-5412a253c8e6
      z: 2
Resources:
  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    DependsOn:
      - VPC
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        'Fn::Join':
          - ''
          - - Ref: AvailabilityZone1
      CidrBlock:
        Ref: PublicSubnetCidrBlock1
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - ''
              - - Ref: Environment
                - '-public-'
                - Ref: AvailabilityZone1
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
        - Key: DeleteAfter
          Value:
            Ref: DeleteAfter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 84f826b0-6248-4d87-b744-5412a253c8e6
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - ''
              - - Ref: Environment
                - '-public-'
                - Ref: AvailabilityZone1
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
        - Key: DeleteAfter
          Value:
            Ref: DeleteAfter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c7f32c56-83fa-4b63-aa08-d3a0dd03de75
  GatewayToInternet:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: db636478-6f20-4326-bcf4-e585dea063da
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    DependsOn:
      - VPC
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - ''
              - - Ref: Environment
                - '-public-'
                - Ref: AvailabilityZone1
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
        - Key: DeleteAfter
          Value:
            Ref: DeleteAfter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4653b995-371c-4add-bd1d-b86b5559a692
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn:
      - PublicRouteTable
      - InternetGateway
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ab79ddd6-62be-40d4-bb04-dcc350f38905
  PublicSubnetAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    DependsOn:
      - PublicSubnet1
      - PublicRouteTable
    Properties:
      SubnetId:
        Ref: PublicSubnet1
      RouteTableId:
        Ref: PublicRouteTable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ff3b287f-4b9a-48bf-9907-7816948f5f21
  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    DependsOn:
      - VPC
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        'Fn::Join':
          - ''
          - - Ref: AvailabilityZone1
      CidrBlock:
        Ref: PrivateSubnetCidrBlock1
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - ''
              - - Ref: Environment
                - '-private-'
                - Ref: AvailabilityZone1
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
        - Key: DeleteAfter
          Value:
            Ref: DeleteAfter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ec7cf0b8-12c0-4199-a48c-e54e015b225c
  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    DependsOn:
      - VPC
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - ''
              - - Ref: Environment
                - '-private-'
                - Ref: AvailabilityZone1
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
        - Key: Environment
          Value:
            Ref: Environment
        - Key: DeleteAfter
          Value:
            Ref: DeleteAfter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 32c6ca3c-7eb1-4b0b-bbe3-cb854f52aaab
  PrivateSubnetAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    DependsOn:
      - PrivateSubnet1
      - PrivateRouteTable
    Properties:
      SubnetId:
        Ref: PrivateSubnet1
      RouteTableId:
        Ref: PrivateRouteTable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7f152eee-0108-433b-a2e8-584a05296cbb
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      CidrBlock:
        Ref: VPCSubnetCidrBlock
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - ''
              - - Ref: Environment
                - '-'
                - Ref: 'AWS::StackName'
        - Key: Owner
          Value:
            Ref: Owner
        - Key: Project
          Value:
            Ref: Project
        - Key: DeleteAfter
          Value:
            Ref: DeleteAfter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 40ea6922-a2db-4c32-882c-3016803e0987
Outputs:
  Owner:
    Description: Team or Individual that Owns this Formation.
    Value:
      Ref: Owner
  Project:
    Description: The project name
    Value:
      Ref: Project
  Environment:
    Description: The Environment name
    Value:
      Ref: Environment
  VPC:
    Description: Created VPC
    Value:
      Ref: VPC
  VPCCIDR:
    Description: VPC Subnet CIDR Block
    Value:
      Ref: VPCSubnetCidrBlock
  PublicRouteTable:
    Description: Public Route Table Created for VPC
    Value:
      Ref: PublicRouteTable
  PrivateRouteTable:
    Description: Private Route Table Created for VPC
    Value:
      Ref: PrivateRouteTable
  PublicSubnet1:
    Description: Public Subnet 1 Created for VPC
    Value: PublicSubnet1
  PrivateSubnet1:
    Description: Private Subnet 1 Created for VPC
    Value:
      Ref: PrivateSubnet1
  AvailabilityZone1:
    Description: Private Subnet IDs Created for VPC
    Value:
      'Fn::GetAtt':
        - PublicSubnet1
        - AvailabilityZone
  PublicSubnetCidr1:
    Description: Public Subnet IDs Created for VPC
    Value:
      Ref: PublicSubnetCidrBlock1
  PrivateSubnetCidr1:
    Description: Private Subnet IDs Created for VPC
    Value:
      Ref: PrivateSubnetCidrBlock1
  InternetGateway:
    Description: Internet Gateway Created for VPC
    Value:
      Ref: InternetGateway
  DeleteAfter:
    Description: It is ok to delete this Formation after this date
    Value:
      Ref: DeleteAfter
